<Project>
    <PropertyGroup>
        <PenguinToolsMuaRoot>$(MSBuildThisFileDirectory)..\External\mua</PenguinToolsMuaRoot>
        <PenguinToolsMuaPublishDir>$(PenguinToolsMuaRoot)\target\release\mua</PenguinToolsMuaPublishDir>
        <PenguinToolsFfmpegRoot>$(MSBuildThisFileDirectory)..\External\ffmpeg</PenguinToolsFfmpegRoot>
        <PenguinToolsFfmpegPublishDir>$(PenguinToolsFfmpegRoot)\bin</PenguinToolsFfmpegPublishDir>
    </PropertyGroup>

    <ItemGroup>
        <_MuaPublishFile Include="$(PenguinToolsMuaPublishDir)\**\*"/>
        <PenguinToolsMuaContent Include="@(_MuaPublishFile)">
            <PublishPath>assets\mua\%(RecursiveDir)%(Filename)%(Extension)</PublishPath>
        </PenguinToolsMuaContent>
        <_FfmpegPublishFile Include="$(PenguinToolsFfmpegPublishDir)\**\*"/>
        <PenguinToolsFfmpegContent Include="@(_FfmpegPublishFile)">
            <PublishPath>assets\ffmpeg\%(RecursiveDir)%(Filename)%(Extension)</PublishPath>
        </PenguinToolsFfmpegContent>
        <PenguinToolsInfrastructureAsset Include="$(MSBuildThisFileDirectory)..\Assets\assets.json">
            <ResourceName>assets.json</ResourceName>
            <ManifestKey>AssetsJson</ManifestKey>
            <PublishPath>assets\assets.json</PublishPath>
        </PenguinToolsInfrastructureAsset>
    </ItemGroup>

    <ItemGroup>
        <Content Include="@(PenguinToolsMuaContent)">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <TargetPath>%(PublishPath)</TargetPath>
            <Link>%(PublishPath)</Link>
        </Content>
        <Content Include="@(PenguinToolsFfmpegContent)">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <TargetPath>%(PublishPath)</TargetPath>
            <Link>%(PublishPath)</Link>
        </Content>
        <Content Include="@(PenguinToolsInfrastructureAsset)">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <TargetPath>%(PublishPath)</TargetPath>
            <Link>%(PublishPath)</Link>
        </Content>
    </ItemGroup>
</Project>
