<Project>
    <PropertyGroup>
        <PenguinToolsTexconvDirectory>$(MSBuildThisFileDirectory)..\artifacts\tools\texconv</PenguinToolsTexconvDirectory>
        <PenguinToolsFfmpegPublishDir>$(MSBuildThisFileDirectory)..\artifacts\tools\ffmpeg</PenguinToolsFfmpegPublishDir>
    </PropertyGroup>

    <ItemGroup>
        <PenguinToolsTexconvContent Include="$(PenguinToolsTexconvDirectory)\texconv.exe;$(MSBuildThisFileDirectory)Licenses\DirectXTex.txt">
            <PublishPath>assets\texconv\%(Filename)%(Extension)</PublishPath>
        </PenguinToolsTexconvContent>
        <PenguinToolsInfrastructureAsset Include="$(MSBuildThisFileDirectory)..\Assets\assets.json">
            <ResourceName>assets.json</ResourceName>
            <ManifestKey>AssetsJson</ManifestKey>
            <PublishPath>assets\assets.json</PublishPath>
        </PenguinToolsInfrastructureAsset>
    </ItemGroup>

    <ItemGroup>
        <Content Include="$(MSBuildThisFileDirectory)Licenses\NetVips.txt;$(MSBuildThisFileDirectory)Licenses\LGPL-3.0.txt;$(MSBuildThisFileDirectory)Licenses\GPL-3.0.txt;$(MSBuildThisFileDirectory)Licenses\libvips-THIRD-PARTY-NOTICES.md;$(MSBuildThisFileDirectory)Licenses\libvips-versions.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <TargetPath>assets\licenses\%(Filename)%(Extension)</TargetPath>
            <Link>assets\licenses\%(Filename)%(Extension)</Link>
        </Content>
        <Content Include="@(PenguinToolsTexconvContent)">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <TargetPath>%(PublishPath)</TargetPath>
            <Link>%(PublishPath)</Link>
        </Content>
        <Content Include="@(PenguinToolsInfrastructureAsset)">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <TargetPath>%(PublishPath)</TargetPath>
            <Link>%(PublishPath)</Link>
        </Content>
    </ItemGroup>
</Project>
