// <auto-generated />
namespace PenguinTools.Assets;
public static partial class InfrastructureResourceNames
{
public const string AssetsJson = "assets.json";
public static readonly string[] All =
[
"assets.json",
];
}
